version: '3.4'

services:
  msschool.presentation.api:
    image: ${DOCKER_REGISTRY-}msschoolpresentationapi
    build:
      context: .
      dockerfile: MSschool.Presentation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5106:5106"

networks:
  default:
    external:
      name: nat
