// <auto-generated />
using System;
using MSschool.Infrastructure.EntityFramework.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSschool.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(MsschoolContext))]
    partial class MsschoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MSschool.Application.Domain.AcademicLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SemesterQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AcademicLevels");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicProgramUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdAcademicProgram")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademicProgram");

                    b.HasIndex("IdUser");

                    b.ToTable("AcademicProgramUsers");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicsProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademicDirector")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademicLevel")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInstitution")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProgramStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademicDirector");

                    b.HasIndex("IdAcademicLevel");

                    b.HasIndex("IdInstitution");

                    b.ToTable("AcademicsPrograms");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c4bc516-21eb-47cd-a594-88195eff6f62"),
                            Availability = false,
                            Description = "Persona que presta los servicios de docencia a la institución.",
                            Name = "Docente"
                        },
                        new
                        {
                            Id = new Guid("6a852be9-7eef-4005-b2f6-0b4edad96394"),
                            Availability = false,
                            Description = "Persona que se encuentra estudiando a la institución.",
                            Name = "Estudiante"
                        });
                });

            modelBuilder.Entity("MSschool.Application.Domain.CourseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NoteValue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentages")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubject");

                    b.HasIndex("IdTeacher");

                    b.HasIndex("IdUser");

                    b.ToTable("CourseNotes");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdAcademicProgram")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("date");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademicProgram");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreRequisite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("MSschool.Application.Domain.SubjectValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Iva")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("IdSubject");

                    b.ToTable("SubjectValues");
                });

            modelBuilder.Entity("MSschool.Application.Domain.SubjectsAcademicProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademicProgram")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademicProgram");

                    b.HasIndex("IdSubject");

                    b.ToTable("SubjectsAcademicProgram", (string)null);
                });

            modelBuilder.Entity("MSschool.Application.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressOfDomicile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CityOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityOfDomicile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryOfBirth")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryOfDomicile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentOdDomicile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndicativeCountryOfBirth")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("IndicativeCountryOfDomicile")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondSurname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MSschool.Application.Domain.UserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubject");

                    b.HasIndex("IdUser");

                    b.ToTable("UserAssignments");
                });

            modelBuilder.Entity("MSschool.Application.Domain.UserCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUser");

                    b.ToTable("UserCategories");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicProgramUser", b =>
                {
                    b.HasOne("MSschool.Application.Domain.AcademicsProgram", "IdAcademicProgramNavigation")
                        .WithMany("AcademicProgramUsers")
                        .HasForeignKey("IdAcademicProgram")
                        .HasConstraintName("FK_AcademicProgramUsers_AcademicsPrograms");

                    b.HasOne("MSschool.Application.Domain.User", "IdUserNavigation")
                        .WithMany("AcademicProgramUsers")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_AcademicProgramUsers_Users");

                    b.Navigation("IdAcademicProgramNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicsProgram", b =>
                {
                    b.HasOne("MSschool.Application.Domain.User", "IdAcademicDirectorNavigation")
                        .WithMany("AcademicsPrograms")
                        .HasForeignKey("IdAcademicDirector")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicsPrograms_Users");

                    b.HasOne("MSschool.Application.Domain.AcademicLevel", "IdAcademicLevelNavigation")
                        .WithMany("AcademicsPrograms")
                        .HasForeignKey("IdAcademicLevel")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicsPrograms_AcademicLevels");

                    b.HasOne("MSschool.Application.Domain.Institution", "IdInstitutionNavigation")
                        .WithMany("AcademicsPrograms")
                        .HasForeignKey("IdInstitution")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicsPrograms_Institutions");

                    b.Navigation("IdAcademicDirectorNavigation");

                    b.Navigation("IdAcademicLevelNavigation");

                    b.Navigation("IdInstitutionNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.CourseNote", b =>
                {
                    b.HasOne("MSschool.Application.Domain.Subject", "IdSubjectNavigation")
                        .WithMany("CourseNotes")
                        .HasForeignKey("IdSubject")
                        .IsRequired()
                        .HasConstraintName("FK_CourseNotes_Subjects");

                    b.HasOne("MSschool.Application.Domain.User", "IdTeacherNavigation")
                        .WithMany("CourseNoteIdTeacherNavigations")
                        .HasForeignKey("IdTeacher")
                        .IsRequired()
                        .HasConstraintName("FK_CourseNotes_Teacher");

                    b.HasOne("MSschool.Application.Domain.User", "IdUserNavigation")
                        .WithMany("CourseNoteIdUserNavigations")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_CourseNotes_User");

                    b.Navigation("IdSubjectNavigation");

                    b.Navigation("IdTeacherNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Schedule", b =>
                {
                    b.HasOne("MSschool.Application.Domain.AcademicsProgram", "IdAcademicProgramNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("IdAcademicProgram")
                        .HasConstraintName("FK_Schedules_AcademicsPrograms");

                    b.Navigation("IdAcademicProgramNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.SubjectValue", b =>
                {
                    b.HasOne("MSschool.Application.Domain.Subject", "IdSubjectNavigation")
                        .WithMany("SubjectValues")
                        .HasForeignKey("IdSubject")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectValues_Subjects");

                    b.Navigation("IdSubjectNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.SubjectsAcademicProgram", b =>
                {
                    b.HasOne("MSschool.Application.Domain.AcademicsProgram", "IdAcademicProgramNavigation")
                        .WithMany("SubjectsAcademicPrograms")
                        .HasForeignKey("IdAcademicProgram")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectsAcademicProgram_AcademicsPrograms");

                    b.HasOne("MSschool.Application.Domain.Subject", "IdSubjectNavigation")
                        .WithMany("SubjectsAcademicPrograms")
                        .HasForeignKey("IdSubject")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectsAcademicProgram_Subjects");

                    b.Navigation("IdAcademicProgramNavigation");

                    b.Navigation("IdSubjectNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.UserAssignment", b =>
                {
                    b.HasOne("MSschool.Application.Domain.Subject", "IdSubjectNavigation")
                        .WithMany("UserAssignments")
                        .HasForeignKey("IdSubject")
                        .HasConstraintName("FK_UserAssignments_Subjects");

                    b.HasOne("MSschool.Application.Domain.User", "IdUserNavigation")
                        .WithMany("UserAssignments")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_UserAssignments_Users");

                    b.Navigation("IdSubjectNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.UserCategory", b =>
                {
                    b.HasOne("MSschool.Application.Domain.Category", "IdCategoryNavigation")
                        .WithMany("UserCategories")
                        .HasForeignKey("IdCategory")
                        .HasConstraintName("FK_UserCategories_Categories1");

                    b.HasOne("MSschool.Application.Domain.User", "IdUserNavigation")
                        .WithMany("UserCategories")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_UserCategories_Categories");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicLevel", b =>
                {
                    b.Navigation("AcademicsPrograms");
                });

            modelBuilder.Entity("MSschool.Application.Domain.AcademicsProgram", b =>
                {
                    b.Navigation("AcademicProgramUsers");

                    b.Navigation("Schedules");

                    b.Navigation("SubjectsAcademicPrograms");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Category", b =>
                {
                    b.Navigation("UserCategories");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Institution", b =>
                {
                    b.Navigation("AcademicsPrograms");
                });

            modelBuilder.Entity("MSschool.Application.Domain.Subject", b =>
                {
                    b.Navigation("CourseNotes");

                    b.Navigation("SubjectValues");

                    b.Navigation("SubjectsAcademicPrograms");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("MSschool.Application.Domain.User", b =>
                {
                    b.Navigation("AcademicProgramUsers");

                    b.Navigation("AcademicsPrograms");

                    b.Navigation("CourseNoteIdTeacherNavigations");

                    b.Navigation("CourseNoteIdUserNavigations");

                    b.Navigation("UserAssignments");

                    b.Navigation("UserCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
